### ISSUE TITLE
Error when logging in 

### ISSUE THREAD

**Issue by jibujaman** [hunterjm/futgui#108]
I self compiled and ran 'python3 'FIFA Auto Buyer 17.py'. After putting in the login information the first time without access code, no error is shown in the terminal. After trying to re-login with the access code, the open window still says 'Futerror: Incorrect code provided.' EA sends me the same code again. Meanwhile, in the terminal the following error message shows up.

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 75, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x107877a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: http://www.easports.com/fifa/login_check?state=7yD3-ytZGfROZY2ALNz0M2E6oi9KE57oVpiQ-HAngBk&code=QUOQAHVZTc5sFR_0qTPxUHUc31D_AH4zRoqtzdvOAQ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x107877a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mybin/fut/futgui/frames/login.py", line 126, in login
    self.controller.api = DelayedCore(self.username.get(), self.password.get(), self.secret.get(), self.platform.get(), self.code.get(), emulate, False, cookies_file)
  File "/Users/mybin/fut/futgui/api/delayedcore.py", line 15, in **init**
    super(DelayedCore, self).**init**(email, passwd, secret_answer, platform, code, emulate, debug, cookies)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fut/core.py", line 166, in **init**
    self.**login**(email, passwd, secret_answer, platform, code, emulate)
  File "/Users/mybin/fut/futgui/api/delayedcore.py", line 31, in **login**
    result = super(DelayedCore, self).**login**(email, passwd, secret_answer, platform, code, emulate)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fut/core.py", line 269, in **login**
    rc = self.r.post(url.replace('s2', 's3'), {'_eventId': 'cancel', 'appDevice': 'IPHONE'}).text
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 177, in resolve_redirects
    *_adapter_kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: http://www.easports.com/fifa/login_check?state=7yD3-ytZGfROZY2ALNz0M2E6oi9KE57oVpiQ-HAngBk&code=QUOQAHVZTc5sFR_0qTPxUHUc31D_AH4zRoqtzdvOAQ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x107877a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/**init**.py", line 1550, in **call**
    return self.func(*args)
  File "/Users/mybin/fut/futgui/frames/login.py", line 142, in login
    self.loginlbl.config(text='\nError logging in: %s (%s)' % (e.reason, type(e).**name**))
AttributeError: 'ProxyError' object has no attribute 'reason'

**Comment by hunterjm** [comment]
This looks like the same issue you had here: https://github.com/oczkers/fut/issues/201

Not sure what causes this one though.
