### ISSUE TITLE
Login?

### ISSUE THREAD

**Issue by FlareRare** [hunterjm/futgui#112]
I get this error when i try to login, it says this error and then its stuck in the blue screen on the gui.

**Comment by FlareRare** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter__init__.py", line 1549, in **call**
  File "C:\Users\Jason\Documents\GitHub\futgui\frames\login.py", line 126, in login
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 15, in **init**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 166, in **init**
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 31, in **login**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 305, in **login**
KeyError: 'userAccountInfo'

**Comment by hunterjm** [comment]
Is the transfer market enabled on the webapp?  Can you search, buy, sell, players with the account you are trying to use?

**Comment by FlareRare** [comment]
Yeah it is, i was just using on the web app
