### ISSUE TITLE
Start bidding error

### ISSUE THREAD

**Issue by Scortchhh** [hunterjm/futgui#115]
Process Process-1:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 50, in bid
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 679, in watchlist

  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 448, in **get**
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 42, in
**request**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 440, in __request
__
fut.exceptions.UnknownError: {'string': '', 'code': '494', 'debug': '', 'reason'
: ''}

**Comment by Scortchhh** [comment]
Using this version: https://github.com/hunterjm/futgui/releases/download/v1.1.1/FIFA.17.Auto.Buyer-v1.1.1-Windows.zip

**Comment by hunterjm** [comment]
Please utilize the issue search feature: https://github.com/hunterjm/futgui/issues/75
