### ISSUE TITLE
errors (ps4)

### ISSUE THREAD

**Issue by vladvenger** [hunterjm/futgui#129]
I get this error:
Process Process-2:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-3:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-4:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-5:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-6:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-7:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-8:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-9:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-10:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-11:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-12:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-13:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-14:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-15:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'

**Comment by darfinx** [comment]
it means you have some cards in tp that is not support from futgui. 

Get Outlook for iOS

On Sat, Oct 15, 2016 at 3:46 PM +0300, "vladvenger" notifications@github.com wrote:

I get this error:

Process Process-2:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-3:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-4:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-5:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-6:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-7:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-8:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-9:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-10:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-11:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-12:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-13:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-14:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

Process Process-15:

Traceback (most recent call last):

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap

  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run

  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid

KeyError: 'Desc'

**Comment by vladvenger** [comment]
Thanks for the response. Im running the bot on win 10. How exactly to i fix
this error? Do I remove all of the players from my transfer list in FIFA
17? or are you talking about the players I added on the bot?

**Comment by darfinx** [comment]
you can do this mobile app, console and web app wherever you want

Get Outlook for iOS

```
    _____________________________
```
