### ISSUE TITLE
exception when seaching Sterling

### ISSUE THREAD

**Issue by hyoussef** [hunterjm/futgui#140]
Always happen when searching Sterling 

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "/Users/i060356/git/personal/futgui/frames/playersearch.py", line 137, in lookup
    self.load_player(r.get(), response['items'][i])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
ValueError: bad transparency mask
```

I never succeed to add it to the players pipe.
- shell console on Mac os sierra

**Comment by JSystem1** [comment]
I also am having this problem, Not only for sterling but many players cant be added
