### ISSUE TITLE
Error when searching for players that currently have an "Ultimate Scream" card

### ISSUE THREAD

**Issue by ghost** [hunterjm/futgui#145]
Exception in Tkinter callback
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\pool.py", line 119, in worker
  File "C:\Users\Jason\Documents\GitHub\futgui\core\playercard.py", line 36, in create
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\site-packages\PIL\Image.py", line 1319, in paste
ValueError: bad transparency mask
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter__init__.py", line 1549, in **call**
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter__init__.py", line 596, in callit
  File "C:\Users\Jason\Documents\GitHub\futgui\frames\playersearch.py", line 137, in lookup
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\pool.py", line 608, in get
ValueError: bad transparency mask

**Comment by Fotospecht** [comment]
Would be real nice if this could be fixed, because the NIF version of the players who have a Halloween version can not be added to the list of players.
