### ISSUE TITLE
Error since today

### ISSUE THREAD

**Issue by Gsoul2k9** [hunterjm/futgui#155]
Hey guys i am getting when i try to start the programm. Anyone got a fix for that?

Exception in Tkinter callback
Traceback (most recent call last):
File "c:\users\jason\appdata\local\programs\python\pyth on35-32\lib\tkinter__init__.py", line 1549, in **call**
File "C:\Users\Jason\Documents\GitHub\futgui\frames\log in.py", line 126, in login
File "C:\Users\Jason\Documents\GitHub\futgui\api\delaye dcore.py", line 15, in **init**
File "C:\Users\Jason\Documents\GitHub\fut\fut\core. py", line 166, in **init**
File "C:\Users\Jason\Documents\GitHub\futgui\api\delaye dcore.py", line 31, in **login**
File "C:\Users\Jason\Documents\GitHub\fut\fut\core. py", line 285, in **login**
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by alexeyvolodin** [comment]
I have same problem, it started today too

**Comment by marlonespindola** [comment]
I AM having the same problema. Also when i try to access the webapp its no working for me... So i think its a temp ban. Since on my celphone its working fine

**Comment by jchengl** [comment]
It is not a temporary ban (Web App is working for me), they might have updated it, was down for a few hours yesterday night.

Edit:
After a few retries, I was able to log into the autobuyer. Seems that the Web App server is having issues...

**Comment by Ahzumer** [comment]
same problem here

**Comment by gala2000** [comment]
i have got the same problem. someone solved the problem?

**Comment by jchengl** [comment]
There's nothing that the dev can fix, EA is having server issues.

**Comment by Dumbbelly29** [comment]
Problem not server sided - can be fixed by logging in on console/PC and clicking transfer market and then searching any player... log back out & bot will work again. Seems to get stuck at the notification of Halloween players stat boost, if you get 500 error you will need to start all over from the beginning. 

Ps, cross your fingers when changing emulation as if you get 500 error again you will need to start from beginning also... :'(   

EDIT: IGNORE ME WORKED EARLIER 5 TIMES IN A ROW NOW NOTHING WORKS
all of my accounts have gone down at the same time can't get on web app even from browser now

**Comment by gala2000** [comment]
it doesn't work :(

**Comment by darfinx** [comment]
same for me.

**Comment by Ahzumer** [comment]
sometimes it workes , sometimes it dont .

**Comment by lifez** [comment]
same here
