### ISSUE TITLE
Simple Tutorial

### ISSUE THREAD

**Issue by hunterjm** [hunterjm/futgui#16]
I don't really have time to make a tutorial, but I think a simple tutorial would be useful for people who haven't used an Auto Bidder/Buyer before.  Anyone willing to help out?

**Comment by fabianofrancesconi** [comment]
Can you elaborate more about this AB? AB-testing?

**Comment by hunterjm** [comment]
I'm not sure I understand your question.  What would you like to know?

**Edit**: Ah, you meant the abbreviation?  AB = Auto Buyer/Bidder.  I edited the initial comment

**Comment by shuohan27** [comment]
Copied and updated for 0.7.1 from my 11/26 post:

Installation/setup:
1. Download the appropriate installer for your platform (zip for PC, dmg for mac)
2. extract the files from the zip or dmg into a suitable folder (right click, extract all for zip; mount DMG and drag somewhere or run straight from mounted DMG)
3. Find and run "Fifa 16 Auto Buyer" wherever you extracted/mounted the files
4. Provide your username/pass/secret answer and try to login.  The secret answer is for the question associated with your FUT account that you made when setting up FUT 16.  This first logon attempt is only to get EA to send you the passcode for you to allow the program to access your account.  This passcode is associated with your EA account.
5. Check e-mail (or sms) for passcode.  This is the authentication passcode sent to your designated e-mail account ensuring you're the one allowing the program to access your account.
6. Re-enter user/pass/secret answer/passcode to log on.  This time, with the passcode entered, you'll be able to log onto your account with the program.  You'll know you're successful if you see the number of credits pop up.  If you're still unable to log in, it will give you an error message like incorrect password, incorrect secret answer, etc.  Please recheck and try again.

Operation:
7. Once logged in, start adding players by searching for the names and clicking on the pictures to add them to your list.  The more players you add, the longer it takes to search through them all and the less likely you will be to snipe a low cost BIN.
8. Now that you have your target players listed, go down in the list and specify Highest bid, Starting selling price, and BIN price for each player.  The highest bid is what the program will bid up to.  It'll also snipe any BIN auction under that price.  The starting selling price and BIN price is what it relists that won card at.
9. When you're all set, click start bidding and you'll go to the next menu.
10. Now you'll have several more parameters to set.
*RPM is requests per minute; this controls how quickly the program goes through its actions.  The higher you set the RPM, the more likely you are to receive a ban.  Typical values are 10-30.
*Min $ specifies the lowest amount of coins the program will allow in  your account.  It will only attempt to not go lower than this, sometimes it may breach this threshold.
*Max Cards specifies the maximum number of one particular card the program will purchase/sell at any given time
*BIN snipe when checked will make the program only purchase BIN items at or below your Max bid price, with no bidding at all.
*Auto update when checked will cause the program check the market for the lowest BIN price of each card in your list.  The following three parameters are percentages of this lowest BIN price it will set the max bid, sell price, and BIN price for each of your selected targets.
*Same Relist $ when checked specifies that when relisting an auction it will always relist it at whatever it was originally listed at.  When unchecked, an auction may be relisted at the currently set price, changed by the auto update routine.
11. When everything is set to your liking, go ahead and click start bidding one more time.  You can now watch what the program is doing in the console window to the right.  You'll also see players you're bidding on and selling in the window above the console.

Hope that helps!

**Comment by ESTM4rkz** [comment]
Hey,
I'm using v0.7.2 windows files, but can't get it to log in. CMD says:

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter\__i
nit__.py", line 1549, in __call__
  File "C:\Users\Jason\Documents\GitHub\futgui\frames\login.py", line 126, in lo
gin
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 15, in
__init__
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 145, in __init__
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 31, in
__login__
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 282, in __login__

TypeError: argument of type 'NoneType' is not iterable

**Comment by Mglt-b** [comment]
*Max Cards specifies the maximum number of one particular card the program will purchase/sell at any given time

I don't understand, it's maximum card / player or maximum total cards on transfert list?

**Comment by Mglt-b** [comment]
Translate for french players : 

Installation:
Télécharger la version appropriée à votre plateforme (zip for PC, dmg for mac)

Extraire les fichiers du zip ou du dmg dans un nouveau dossier (clique droit, extraire tout pour zip; monter le DMG et glisser quelque part ou lancer directement à partir du DMG monté)

Trouver et lancer "Fifa 17 Auto Buyer" où vous avez extrait les fichiers.

Entre votre adresse mail, votre mot de passe et la réponse à la question secrête.
La question secrête à été définie à la création de votre compte EA. 
Tentez de vous connectez en laissant le champ 'passcode' vide, vous devriez recevoir un mail avec le code. 
Entre ce code et tentez à nouveau de vous connecter.
Si ça ne fonctionne pas, il y a une valeur mal renseignée quelque part.

Utilisation du bot : 

Une fois connecté, il faut ajouter des joueurs sur lesquels vous allez enchérir.
Dans la barre blanche en haut entrez le nom d'un joueur, une ou plusieurs images devraient apparaître.
Cliquez sur le joueur (la carte) voulue, une ligne s'ajoute dans le tableau.

Ici 3 valeurs à remplir : 
Max bid ; enchère maximum que vous voulez mettre pour le joueur
Starting selling price ; prix d'enchère auquel le bot liste le joueur
BIN price ; prix d'achat d'immédiat quand le bot liste le joueur

Quand vous avez terminé votre liste de joueur et de définir les prix, cliquez sur "start biding".
Vous accédez au menu suivant.

Dans ce nouveau menu vous avez plusieurs paramètres.

*RPM = requêtes par minute; 
Plus vous mettez une valeur haute plus vous risquez un ban. 
Valeurs conseillées entre 10-30.

*Min $ = crédits à conserver sur le compte

*Max Cards specifies the maximum number of one particular card the program will purchase/sell at any given time [difficultés de traduction]

*BIN snipe when checked will make the program only purchase BIN items at or below your Max bid price, with no bidding at all. [difficultés de traduction]

*Auto update = si coché, le programme va mettre à jour les prix défini dans le menu précédent tout seul, en analysant les prix du marché.

*Same Relist $ = relister les joueurs au même prix

Quand tout est ok, cliquez sur start bidding.

Si vous avez l'erreur 500, c'est un ban temporaire.
C'est du à un trop gros nombre de requête ou une activité trop longue.
Pour y remédier, essayez de baisser le nombre de RPM, ou de faire des plus courtes sessions.

Un ban temporaire est actif sur une seule plateforme d'émulation. Si vous avez été temporairement banni avec la plateforme PC, vous pouvez continuer avec la plateforme android ou IOS.
