### ISSUE TITLE
Bidcycle not working - Futgui is bidding but not clearing the watchlist and not offering the won players

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/futgui#160]
I have an account that behaves strange and the Bidcycle is not working correctly.

This account has different personas, but futgui is picking up the correct persona so I expected it would work fine.

Futgui is watching players and also bidding with this account, but the Futgui log window does not display these events, only the "Updating prices" event can be seen. Also the top right list of players is not populated.

In the web app I can see that the watched players are not removed from the watchlist and the won players are not listed.

I can see the error below in the console:

Process Process-19:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/shuebner/Downloads/futgui-1.1.1/core/bid.py", line 58, in bid
    asset = api.cardInfo(trade['resourceId'])
  File "/Users/shuebner/Downloads/futgui-1.1.1/api/delayedcore.py", line 67, in cardInfo
    result = super(DelayedCore, self).cardInfo(resource_id)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fut/core.py", line 540, in cardInfo
    return requests.get(url).json()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Fotospecht** [comment]
I found that this problem is not related to the account,
instead the error apperas because some of the players are not working.
I could reproduce this problem on another account.

Examples:
Zuculini 76
Mercado
Edenilson
