### ISSUE TITLE
I keep getting error when Started Bid Action whatever in my Own Build or Pre build Version

### ISSUE THREAD

**Issue by kkentam** [hunterjm/futgui#25]
**if using Pre-Build version (0.7.1 and 0.7.0)**

```
Process Process-1:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
Process Process-2:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'
```

---

**if using my own Build version (0.7.1 and 0.7.0)**

```
Process Process-1:
Traceback (most recent call last):
  File "c:\users\kken\appdata\local\programs\python\python35-32\lib\multiprocess
ing\process.py", line 254, in _bootstrap
    self.run()
  File "c:\users\kken\appdata\local\programs\python\python35-32\lib\multiprocess
ing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\_FIFA 16 Autobuyer\futgui-0.7.1-beta\futgui-0.7.1-beta\core\
bid.py", line 62, in bid
    displayName = asset['Item']['Desc']
KeyError: 'Desc'
Process Process-2:
Traceback (most recent call last):
  File "c:\users\kken\appdata\local\programs\python\python35-32\lib\multiprocess
ing\process.py", line 254, in _bootstrap
    self.run()
  File "c:\users\kken\appdata\local\programs\python\python35-32\lib\multiprocess
ing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\_FIFA 16 Autobuyer\futgui-0.7.1-beta\futgui-0.7.1-beta\core\
bid.py", line 62, in bid
    displayName = asset['Item']['Desc']
KeyError: 'Desc'
```

Any advises?
Thanks

**Comment by hunterjm** [comment]
@elbryan: It looks like your update to include non-player cards is not working 100% as intended.  Apparently `Desc` is not on all assets.

@kkentam: Clear out your tradepile (Transfer List) in the webapp before starting the auto buyer, and the issue should go away.  We will look into fixing this for the next release.

**Comment by fabianofrancesconi** [comment]
I would rather add a try-except that sets displayName to Unknown in this case. Do you have a working solution for the 100% of the cases?

**Comment by kkentam** [comment]
After clear out my Transfer List (except Player cards), it works now
