### ISSUE TITLE
make macbundle throws error "'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/futgui#46]
I followed the instructions in readme.md to build the executable 0.7.2 on my Mac.
The requirements installed fine with `pip install -r requirements.txt`, however the make throws the following error. Am I still missing a required module ?

```
stefan@Stefans-MacBook-Pro:~/Downloads/futgui-0.7.2-beta$ make macbundle
rm -rf build dist
python3 setup.py py2app --packages=requests
running py2app
creating /Users/stefan/Downloads/futgui-0.7.2-beta/build
creating /Users/stefan/Downloads/futgui-0.7.2-beta/build/bdist.macosx-10.6-intel
creating /Users/stefan/Downloads/futgui-0.7.2-beta/build/bdist.macosx-10.6-intel/python3.5-standalone
creating /Users/stefan/Downloads/futgui-0.7.2-beta/build/bdist.macosx-10.6-intel/python3.5-standalone/app
creating /Users/stefan/Downloads/futgui-0.7.2-beta/build/bdist.macosx-10.6-intel/python3.5-standalone/app/collect
creating /Users/stefan/Downloads/futgui-0.7.2-beta/build/bdist.macosx-10.6-intel/python3.5-standalone/app/temp
creating /Users/stefan/Downloads/futgui-0.7.2-beta/dist
creating build/bdist.macosx-10.6-intel/python3.5-standalone/app/lib-dynload
creating build/bdist.macosx-10.6-intel/python3.5-standalone/app/Frameworks
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    setup_requires=['py2app'],
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/stefan/Downloads/futgui-0.7.2-beta/.eggs/py2app-0.9-py3.5.egg/py2app/build_app.py", line 659, in run
    self._run()
  File "/Users/stefan/Downloads/futgui-0.7.2-beta/.eggs/py2app-0.9-py3.5.egg/py2app/build_app.py", line 865, in _run
    self.run_normal()
  File "/Users/stefan/Downloads/futgui-0.7.2-beta/.eggs/py2app-0.9-py3.5.egg/py2app/build_app.py", line 939, in run_normal
    mf = self.get_modulefinder()
  File "/Users/stefan/Downloads/futgui-0.7.2-beta/.eggs/py2app-0.9-py3.5.egg/py2app/build_app.py", line 814, in get_modulefinder
    debug=debug,
  File "/Users/stefan/Downloads/futgui-0.7.2-beta/.eggs/modulegraph-0.12.1-py3.5.egg/modulegraph/find_modules.py", line 341, in find_modules
  File "/Users/stefan/Downloads/futgui-0.7.2-beta/.eggs/modulegraph-0.12.1-py3.5.egg/modulegraph/find_modules.py", line 266, in find_needed_modules
TypeError: 'NoneType' object is not subscriptable
make: *** [macbundle] Error 1
```

**Comment by conorg** [comment]
Seeing the same issue, did you find a solution for this @Fotospecht ?

**Comment by converge** [comment]
same issue here
