### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by maaarkz** [hunterjm/futgui#47]
Hey,
I'm using v0.7.2 windows files, but can't get it to log in. CMD says:

Exception in Tkinter callback
Traceback (most recent call last):
File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter__i
nit__.py", line 1549, in call
File "C:\Users\Jason\Documents\GitHub\futgui\frames\login.py", line 126, in lo
gin
File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 15, in
init
File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 145, in init
File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 31, in
login
File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 282, in login

TypeError: argument of type 'NoneType' is not iterable

**Comment by maaarkz** [comment]
Hellooouuu? It's me...

I was wondering if after all these months you'd like to help!
