### ISSUE TITLE
Version 1.1.0 does not work

### ISSUE THREAD

**Issue by JonasPap** [hunterjm/futgui#68]
When I want to login there is an error in the cmd window:

,,Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter__i
nit__.py", line 1549, in **call**
  File "C:\Users\Jason\Documents\GitHub\futgui\frames\login.py", line 126, in lo
gin
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 15, in
**init**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 145, in **init**
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 31, in
**login**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 256, in **login**

AttributeError: 'NoneType' object has no attribute 'group'"

I can login into Version 1.0.1 but i do not really understand to make the settings to set up the Autobuyer. Is there any kind of a tutorial how it exatly works?

Thanks for the programm and your help.

If you need I can give you a xbox one account.

**Comment by r9loic** [comment]
Hello, 

Also if you launch from the source code, the autobuyer can buy player from bid or auction, but cannot put resell them.

Here attach message from console : 

![error](https://cloud.githubusercontent.com/assets/16323874/19016669/ba8e1f4c-8821-11e6-931c-2d19b4828025.png)

Thanks for your work

**Comment by hunterjm** [comment]
I just released a new binary for the Windows version that should solve the login issues.

@r9loic - please create a new Issue as it does not appear to be related.
