### ISSUE TITLE
 in version 1.1.1 I can not log 

### ISSUE THREAD

**Issue by JON-GAMES** [hunterjm/futgui#73]
when trying to connect reports the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\tkinter__init__.py", line 1549, in **call**
  File "C:\Users\Jason\Documents\GitHub\futgui\frames\login.py", line 126, in login
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 15, in **init**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 145, in **init**
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 31, in **login**
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 256, in **login**
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Ghost142002** [comment]
I have the same error

**Comment by hunterjm** [comment]
Should be fixed if you re-download the Windows file.

**Comment by JON-GAMES** [comment]
thank you so much.
congratulations for the work.
