### ISSUE TITLE
When i start bidding,this text appears in console

### ISSUE THREAD

**Issue by impavidox** [hunterjm/futgui#76]
Process Process-533:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiprocessing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 62, in bid
KeyError: 'Desc'

**Comment by hunterjm** [comment]
Try removing everything from your transfer list and watchlist.  It's the same bug as last year caused by non-player cards.
