### ISSUE TITLE
The app would not login

### ISSUE THREAD

**Issue by jibujaman** [hunterjm/futgui#77]
I am using your build release for mac. I have done everything correctly as stated in the tutorial posted in a separate issue below. However, it does not connect, sometimes it says "Wrong access code" although I have provided the one I got in email. And now it's not showing any error message.

**Comment by jibujaman** [comment]
I built on my own, and still can't login. Nothing happens after pressing the login button.

**Comment by jibujaman** [comment]
After looking at some other issues, I made sure all the requirements are up-to-date, and then ran `python3.5 'FIFA 17 Auto Buyer.py`.  The login window opens. After filling in my login information and clicking login, nothing happens and this error shows up in the terminal.

>  Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/**init**.py", line 1550, in **call**
>     return self.func(*args)
>   File "/Users/user/fut/futgui/frames/login.py", line 109, in login
>     self.master.config(cursor='wait')
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/**init**.py", line 1330, in configure
>     return self._configure('configure', cnf, kw)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1321, in _configure
>     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
> _tkinter.TclError: bad cursor spec "wait"

**Comment by jibujaman** [comment]
Okay, I am trying to build now and at the end, it shows this:

> Modules not found (conditional imports):
> - Cookie (requests.compat)
> - Image (/Users/anowarjaman/mybin/fut/futgui/.eggs/py2app-0.10-py3.5.egg/py2app/recipes/PIL/prescript.py)
> - StringIO (requests.compat, requests.packages.urllib3.packages.six)
> - Tkinter (PIL._tkinter_finder)
> - _frozen_importlib_external (importlib._bootstrap)
> - cookielib (requests.compat)
> - java (platform)
> - java.lang (platform, xml.sax._exceptions)
> - netbios (uuid)
> - org.python.core (xml.sax)
> - urllib2 (requests.compat)
> - urlparse (requests.compat)
> - win32wnet (uuid)

Done!
